### ISSUE TITLE
Compilation fails with `atomicfu` plugin.

### ISSUE THREAD

**Issue by sureshg** [JavierSegoviaCordoba/kopy#26]
* Env
```
kotlin                         = "2.0.20"
kotlin-ksp                     = "2.0.20-1.0.24"
kotlin-jvmtarget               = "22"
kotlin-api-version             = "2.0"
kotlin-lang-version            = "2.0"
gradle                         = "8.10"
```

I do have a shared module with the following plugins configured.
``` kotlin
  kotlin("multiplatform")
  kotlin("plugin.serialization")
  kotlin("plugin.power-assert")
  kotlin("plugin.js-plain-objects")
  id("plugins.kotlin.docs") // this is dokka
  com.google.devtools.ksp
  org.jetbrains.kotlinx.atomicfu
  dev.zacsweers.redacted
  ```
  
  Apply the new `kopy` plugin and annotate a data class like the following 
  
  ```kotlin
@Kopy
data class Retry(val attempts: Int, val maxDelay: Duration) {
  companion object {
    val DEFAULT = Retry(attempts = 2, maxDelay = 2.seconds)
  }
}
```

The gradle compile kotlin task fails with the following error

```
> Task :shared:compileKotlinJvm
e: java.lang.IllegalStateException: To ensure that atomic properties are not accessed out of the current Kotlin module, it is necessary to declare atomic properties as private or internal.
Please consider declaring [val _atomic: kotlinx.atomicfu.AtomicRef<dev.suresh.http.Retry>] from [CLASS CLASS name:Retry modality:FINAL visibility:public [data] superTypes:[kotlin.Any]] as a private or internal property.
You may also make the containing class [CLASS CLASS name:Retry modality:FINAL visibility:public [data] superTypes:[kotlin.Any]] private or internal.
Alternatively, if you need to expose the atomic property value to the public, you can use a delegated property declared within the same scope, e.g:

private val _a = atomic<T>(initial)
public var a: T by _a

        at org.jetbrains.kotlinx.atomicfu.compiler.backend.common.AbstractAtomicfuTransformer$AtomicPropertiesTransformer.checkVisibility(AbstractAtomicfuTransformer.kt:463)
        at org.jetbrains.kotlinx.atomicfu.compiler.backend.common.AbstractAtomicfuTransformer$AtomicPropertiesTransformer.transformAtomicProperty(AbstractAtomicfuTransformer.kt:160)
        at org.jetbrains.kotlinx.atomicfu.compiler.backend.common.AbstractAtomicfuTransformer$AtomicPropertiesTransformer.visitClass(AbstractAtomicfuTransformer.kt:139)
        at org.jetbrains.kotlinx.atomicfu.compiler.backend.common.AbstractAtomicfuTransformer$AtomicPropertiesTransformer.visitClass(AbstractAtomicfuTransformer.kt:134)
        at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:72)
        at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:33)
        at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
        at org.jetbrains.kotlin.ir.declarations.IrFile.transformChildren(IrFile.kt:38)
        at org.jetbrains.kotlin.ir.visitors.IrElementTransformer$DefaultImpls.visitFile(IrElementTransformer.kt:90)
        at org.jetbrains.kotlinx.atomicfu.compiler.backend.common.AbstractAtomicfuTransformer$AtomicPropertiesTransformer.visitFile(AbstractAtomicfuTransformer.kt:151)
        at org.jetbrains.kotlinx.atomicfu.compiler.backend.common.AbstractAtomicfuTransformer$AtomicPropertiesTransformer.visitFile(AbstractAtomicfuTransformer.kt:134)
        at org.jetbrains.kotlin.ir.declarations.IrFile.accept(IrFile.kt:28)
        at org.jetbrains.kotlin.ir.declarations.IrFile.transform(IrFile.kt:31)
        at org.jetbrains.kotlinx.atomicfu.compiler.backend.common.AbstractAtomicfuTransformer.transformAtomicProperties(AbstractAtomicfuTransformer.kt:111)
        at org.jetbrains.kotlinx.atomicfu.compiler.backend.common.AbstractAtomicfuTransformer.transform(AbstractAtomicfuTransformer.kt:97)
        at org.jetbrains.kotlinx.atomicfu.compiler.extensions.AtomicfuLoweringExtension.generate(AtomicfuLoweringExtension.kt:36)
        at org.jetbrains.kotlin.fir.pipeline.ConvertToIrKt.applyIrGenerationExtensions(convertToIr.kt:437)
        at org.jetbrains.kotlin.fir.pipeline.Fir2IrPipeline.runActualizationPipeline(convertToIr.kt:246)
        at org.jetbrains.kotlin.fir.pipeline.Fir2IrPipeline.convertToIrAndActualize(convertToIr.kt:130)
        at org.jetbrains.kotlin.fir.pipeline.ConvertToIrKt.convertToIrAndActualize(convertToIr.kt:99)
        at org.jetbrains.kotlin.fir.pipeline.ConvertToIrKt.convertToIrAndActualize$default(convertToIr.kt:72)
        at org.jetbrains.kotlin.cli.jvm.compiler.pipeline.JvmCompilerPipelineKt.convertToIrAndActualizeForJvm(jvmCompilerPipeline.kt:196)
        at org.jetbrains.kotlin.cli.jvm.compiler.pipeline.JvmCompilerPipelineKt.convertAnalyzedFirToIr(jvmCompilerPipeline.kt:169)
        at org.jetbrains.kotlin.cli.jvm.compiler.pipeline.JvmCompilerPipelineKt.compileModulesUsingFrontendIrAndLightTree(jvmCompilerPipeline.kt:140)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:148)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:43)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:103)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:49)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
```

**Comment by JavierSegoviaCordoba** [comment]
Thank you for the report!

It should be easy to be fixed, I need to generate the property with `by`.
