### ISSUE TITLE
Native compilation error

### ISSUE THREAD

**Issue by sureshg** [JavierSegoviaCordoba/kopy#29]
Just applying the plugin to a common module without any `@Kopy` annotation data class throws the following error
```
> Task :shared:compileKotlinLinuxArm64 FAILED
e: java.lang.NoClassDefFoundError: com/javiersc/kotlin/kopy/args/KopyFunctions
        at com.javiersc.kotlin.kopy.compiler.KopyCommandLineProcessor.processOption(KopyCommandLineProcessor.kt:42)
        at org.jetbrains.kotlin.cli.plugins.PluginsOptionsParserKt.processCompilerPluginOptions(PluginsOptionsParser.kt:85)
        at org.jetbrains.kotlin.cli.plugins.PluginsOptionsParserKt.processCompilerPluginsOptions(PluginsOptionsParser.kt:49)
        at org.jetbrains.kotlin.cli.jvm.plugins.PluginCliParser.processPluginOptions(PluginCliParser.kt:158)
        at org.jetbrains.kotlin.cli.jvm.plugins.PluginCliParser.loadPluginsLegacyStyle(PluginCliParser.kt:147)
        at org.jetbrains.kotlin.cli.jvm.plugins.PluginCliParser.loadPluginsSafe(PluginCliParser.kt:57)
        at org.jetbrains.kotlin.cli.jvm.plugins.PluginCliParser.loadPluginsSafe(PluginCliParser.kt:40)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:55)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:34)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:103)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:49)

```

**Comment by sureshg** [comment]
I am still having issue with the latest version

```
> Task :shared:compileKotlinLinuxArm64 FAILED
e: java.lang.NoClassDefFoundError: com/javiersc/kotlin/kopy/args/KopyFunctions
        at com.javiersc.kotlin.kopy.compiler.KopyCommandLineProcessor.processOption(KopyCommandLineProcessor.kt:42)
        at org.jetbrains.kotlin.cli.plugins.PluginsOptionsParserKt.processCompilerPluginOptions(PluginsOptionsParser.kt:85)
        at org.jetbrains.kotlin.cli.plugins.PluginsOptionsParserKt.processCompilerPluginsOptions(PluginsOptionsParser.kt:49)
        at org.jetbrains.kotlin.cli.jvm.plugins.PluginCliParser.processPluginOptions(PluginCliParser.kt:158)
        at org.jetbrains.kotlin.cli.jvm.plugins.PluginCliParser.loadPluginsLegacyStyle(PluginCliParser.kt:147)
        at org.jetbrains.kotlin.cli.jvm.plugins.PluginCliParser.loadPluginsSafe(PluginCliParser.kt:57)
        at org.jetbrains.kotlin.cli.jvm.plugins.PluginCliParser.loadPluginsSafe(PluginCliParser.kt:40)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:55)
        at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:34)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:103)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:49)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:79)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:43)
```

**Comment by JavierSegoviaCordoba** [comment]
@sureshg can you share a minimal reproducer? 

It is working for me with this setup:

```kotlin
plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kopy)
}

kotlin {
    jvm()
    linuxArm64()
    linuxX64()
    mingwX64()
}
```

**Comment by JavierSegoviaCordoba** [comment]
I have tried to add the `kopy` block to the build field with this

```kotlin
kopy {
    functions = KopyFunctions.Copy
    visibility = KopyVisibility.Public
}
```

But it is still working.

Which OS are you using?

**Comment by sureshg** [comment]
Yeah, will see if I can get a reproducer.  Here is my setup

  1.  I have a shared module which has 
  
  ```kotlin
plugins {
  plugins.kotlin.mpp
  plugins.publishing
  alias(libs.plugins.mappie)
  alias(libs.plugins.kopy)
}
```

2. Using the shared module as dependency on native module

```kotlin
plugins {
  plugins.kotlin.mpp
  com.google.cloud.tools.jib
  plugins.publishing
}

val appBinName = "app"

description = "Ktor native application"

kotlin {
  targets.withType<KotlinNativeTarget>().configureEach {
    binaries {
      executable(setOf(RELEASE)) {
        entryPoint = "main"

        // Fix for libcrypt.so.1 not-found error on distroless
        if (target.targetName.startsWith("linux")) {
          linkerOpts("--as-needed")
          freeCompilerArgs += "-Xoverride-konan-properties=linkerGccFlags.linux=-lgcc -lgcc_eh -lc"
        }

        if (buildType == NativeBuildType.RELEASE) {
          mavenPublication {
            artifact(outputFile) {
              // classifier = target.targetName
            }
          }
        }
      }
    }
  }

  sourceSets {
    commonMain { dependencies { api(projects.shared) } }

...
```

So is the plugin adding those KopyFunctions dependency as implementation or API ?

**Comment by JavierSegoviaCordoba** [comment]
The module that contains KopyFunctions is only shared between the Gradle plugin and the compiler plugin, it is not necessary elsewhere.

I will try to reproduce it.

**Comment by JavierSegoviaCordoba** [comment]
I have cloned your template and with these changes, it is compiling on macOS (Intel).

### `libs.versions.toml`

```diff
[versions]
- java                           = "24"
+ java                           = "21"
kotlin                         = "2.0.20"
kotlin-ksp                     = "2.0.20-1.0.24"
- kotlin-jvmtarget               = "22"
+ kotlin-jvmtarget               = "21"

...

- kopy                           = "0.6.0+2.0.20"
+ kopy                           = "0.7.0+2.0.20"
```

### `shared/build.gradle.kts`

```diff
-   // alias(libs.plugins.kopy)
+   alias(libs.plugins.kopy)
```

I am running `./gradlew shared:assemble` as other projects are failing due to missing classes (I guess you are using Java 24 features and downgrading from 24 fails).

**Comment by sureshg** [comment]
@JavierSegoviaCordoba thanks..could you enable the native module (which will use the shared one) - https://github.com/sureshg/kotlin-mpp-playground/blob/main/gradle.properties#L66 and try

**Comment by JavierSegoviaCordoba** [comment]
> @JavierSegoviaCordoba thanks..could you enable the native module (which will use the shared one) - https://github.com/sureshg/kotlin-mpp-playground/blob/main/gradle.properties#L66 and try

I can reproduce it, but I will have to ask. I have no idea how to fix this except to move the setup to use plain strings.

**Comment by JavierSegoviaCordoba** [comment]
@sureshg I have checked other KMP plugins and their setup is using plain strings, I will publish a version fixing this in some minutes.

**Comment by sureshg** [comment]
@JavierSegoviaCordoba Awesome, it works now. Thanks for fixing it.

**Comment by JavierSegoviaCordoba** [comment]
> @JavierSegoviaCordoba Awesome, it works now. Thanks for fixing it.

You are welcome and thank you for your help 🙏
