### ISSUE TITLE
`2.1.0-Beta1` support.

### ISSUE THREAD

**Issue by sureshg** [JavierSegoviaCordoba/kopy#41]
The plugin now shows this warning. Can we have the official support for 2.1.0 ?

```
Kopy uses a different Kotlin version, 2.0.20, than the Kotlin Gradle plugin applied to this project, 2.1.0-Beta1. It may not work as expected.
```

**Comment by JavierSegoviaCordoba** [comment]
@sureshg I have run all the tests and all of them are passing with version 2.1.0-Beta1, you can ignore that warning :)

Publishing a new version is not straightforward (I need to update Hubdle, publish it, and so on).

As the Kotlin version 2.0.21 will be released soon, I want to provide support for stable versions ASAP and only publish beta/rc versions if the plugin is broken to avoid having problems like downgrading to 2.0.30 if for whatever reason it is released in the future.

**Comment by sureshg** [comment]
Wasmjs compilation fails with the following error on `2.1.0-Beta1`

```
e: org.jetbrains.kotlin.util.FileAnalysisException: While analysing /Users/sgopal1/code/kotlin-mpp-playground/shared/src/commonMain/kotlin/dev/suresh/lang/Person.kt:6:1: java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.fir.symbols.impl.FirRegularClassSymbol org.jetbrains.kotlin.fir.resolve.providers.FirSymbolProviderKt.getRegularClassSymbolByClassId(org.jetbrains.kotlin.fir.resolve.providers.FirSymbolProvider, org.jetbrains.kotlin.name.ClassId)'
        at org.jetbrains.kotlin.util.AnalysisExceptionsKt.wrapIntoFileAnalysisExceptionIfNeeded(AnalysisExceptions.kt:57)
        at org.jetbrains.kotlin.fir.FirCliExceptionHandler.handleExceptionOnFileAnalysis(Utils.kt:249)
        at org.jetbrains.kotlin.fir.resolve.transformers.AbstractFirStatusResolveTransformer.transformFile(FirStatusResolveTransformer.kt:542)
        at org.jetbrains.kotlin.fir.resolve.transformers.AbstractFirStatusResolveTransformer.transformFile(FirStatusResolveTransformer.kt:187)
        at org.jetbrains.kotlin.fir.declarations.FirFile.transform(FirFile.kt:46)
        at org.jetbrains.kotlin.fir.resolve.transformers.FirTransformerBasedResolveProcessor.processFile(FirResolveProcessor.kt:48)
        at org.jetbrains.kotlin.fir.resolve.transformers.FirTotalResolveProcessor.process(FirTotalResolveProcessor.kt:36)
        at org.jetbrains.kotlin.fir.pipeline.AnalyseKt.runResolution(analyse.kt:24)
        at org.jetbrains.kotlin.fir.pipeline.FirUtilsKt.resolveAndCheckFir(firUtils.kt:76)
        at org.jetbrains.kotlin.fir.pipeline.FirUtilsKt.buildResolveAndCheckFirViaLightTree(firUtils.kt:88)
        at org.jetbrains.kotlin.cli.js.klib.JsCompilerPipelineKt.compileModulesToAnalyzedFirWithLightTree(jsCompilerPipeline.kt:194)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.processSourceModuleWithK2(K2JSCompiler.kt:608)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.produceSourceModule(K2JSCompiler.kt:507)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.kt:333)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.kt:101)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:102)
        at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.kt:316)
        at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:200)
        at org.jetbrains.kotlin.incremental.IncrementalJsCompilerRunner.runCompiler(IncrementalJsCompilerRunner.kt:75)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:506)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:423)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:301)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:129)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile$default(IncrementalCompilerRunner.kt:113)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execJsIncrementalCompiler(CompileServiceImpl.kt:608)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execJsIncrementalCompiler(CompileServiceImpl.kt:91)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1757)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:573)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1576)
Caused by: java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.fir.symbols.impl.FirRegularClassSymbol org.jetbrains.kotlin.fir.resolve.providers.FirSymbolProviderKt.getRegularClassSymbolByClassId(org.jetbrains.kotlin.fir.resolve.providers.FirSymbolProvider, org.jetbrains.kotlin.name.ClassId)'
        at com.javiersc.kotlin.kopy.compiler.fir.generation.FirKopyDeclarationGenerationExtension.createAnnotation(FirKopyDeclarationGenerationExtension.kt:408)
        at com.javiersc.kotlin.kopy.compiler.fir.generation.FirKopyDeclarationGenerationExtension.createCopyLikeFunction(FirKopyDeclarationGenerationExtension.kt:390)
        at com.javiersc.kotlin.kopy.compiler.fir.generation.FirKopyDeclarationGenerationExtension.createCopyFun(FirKopyDeclarationGenerationExtension.kt:191)
        at com.javiersc.kotlin.kopy.compiler.fir.generation.FirKopyDeclarationGenerationExtension.generateFunctions(FirKopyDeclarationGenerationExtension.kt:152)
        at org.jetbrains.kotlin.fir.scopes.impl.FirGeneratedMemberDeclarationsStorage$CallableStorage.generateMemberFunctions(FirGeneratedScopes.kt:210)
        at org.jetbrains.kotlin.fir.scopes.impl.FirGeneratedMemberDeclarationsStorage$CallableStorage.access$generateMemberFunctions(FirGeneratedScopes.kt:187)
        at org.jetbrains.kotlin.fir.scopes.impl.FirGeneratedMemberDeclarationsStorage$CallableStorage$special$$inlined$createCache$1.invoke(FirCachesFactory.kt:73)
        at org.jetbrains.kotlin.fir.scopes.impl.FirGeneratedMemberDeclarationsStorage$CallableStorage$special$$inlined$createCache$1.invoke(FirCachesFactory.kt:71)
        at org.jetbrains.kotlin.fir.caches.FirThreadUnsafeCache.getValue(FirThreadUnsafeCachesFactory.kt:40)
        at org.jetbrains.kotlin.fir.scopes.impl.FirGeneratedClassDeclaredMemberScope.processFunctionsByName(FirGeneratedScopes.kt:293)
        at org.jetbrains.kotlin.fir.scopes.FirCompositeScope.processFunctionsByName(FirCompositeScope.kt:57)
        at org.jetbrains.kotlin.fir.scopes.FirNameAwareCompositeScope.processFunctionsByName(FirCompositeScope.kt:90)
        at org.jetbrains.kotlin.fir.scopes.impl.FirClassAnySynthesizedMemberScope.processFunctionsByName(FirClassAnySynthesizedMemberScope.kt:100)
        at org.jetbrains.kotlin.fir.scopes.impl.AbstractFirUseSiteMemberScope.collectDeclaredFunctions(AbstractFirUseSiteMemberScope.kt:79)
        at org.jetbrains.kotlin.fir.scopes.impl.AbstractFirUseSiteMemberScope.collectFunctions(AbstractFirUseSiteMemberScope.kt:73)

```

**Comment by JavierSegoviaCordoba** [comment]
I am going to ask on the compiler as it is existing on the JVM and it does not make sense it has been removed for other.

**Comment by sureshg** [comment]
> Kopy uses a different Kotlin version, 2.0.20, than the Kotlin Gradle plugin applied to this project, 2.1.0-Beta1. It may not work as expected.

Also, it would be great to provide an option to hide the compiler mismatch warning message with a configuration in `kopy {}`

**Comment by sureshg** [comment]
@JavierSegoviaCordoba gentle bump. Is 2.1 support planned anytime soon?

**Comment by JavierSegoviaCordoba** [comment]
I haven't tested the RC ones as I was waiting for the final one. Have you found any issue?

**Comment by sureshg** [comment]
yeah same one as described above

```
> Task :shared:compileKotlinWasmJs FAILED
e: org.jetbrains.kotlin.util.FileAnalysisException: While analysing /../shared/src/commonMain/kotlin/dev/suresh/Greeting.kt:14:16: org.jetbrains.kotlin.util.FileAnalysisException: While analysing /.../shared/src/commonMain/kotlin/dev/suresh/http/HttpClient.kt:21:5: java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.fir.symbols.impl.FirRegularClassSymbol org.jetbrains.kotlin.fir.resolve.providers.FirSymbolProviderKt.getRegularClassSymbolByClassId(org.jetbrains.kotlin.fir.resolve.providers.FirSymbolProvider, org.jetbrains.kotlin.name.ClassId)'
        at org.jetbrains.kotlin.util.AnalysisExceptionsKt.wrapIntoFileAnalysisExceptionIfNeeded(AnalysisExceptions.kt:57)
        at org.jetbrains.kotlin.fir.FirCliExceptionHandler.handleExceptionOnFileAnalysis(Utils.kt:249)
        at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirDeclarationsResolveTransformer.transformFile(FirDeclarationsResolveTransformer.kt:1698)
        at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirAbstractBodyResolveTransformerDispatcher.transformFile(FirAbstractBodyResolveTransformerDispatcher.kt:57)
        at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirAbstractBodyResolveTransformerDispatcher.transformFile(FirAbstractBodyResolveTransformerDispatcher.kt:24)
        at org.jetbrains.kotlin.fir.declarations.FirFile.transform(FirFile.kt:46)
        at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirImplicitTypeBodyResolveTransformerAdapter.transformFile(FirImplicitBodyResolve.kt:72)
        at org.jetbrains.kotlin.fir.declarations.FirFile.transform(FirFile.kt:46)
        at org.jetbrains.kotlin.fir.resolve.transformers.FirTransformerBasedResolveProcessor.processFile(FirResolveProcessor.kt:48)
        at org.jetbrains.kotlin.fir.resolve.transformers.FirTotalResolveProcessor.process(FirTotalResolveProcessor.kt:36)
        at org.jetbrains.kotlin.fir.pipeline.AnalyseKt.runResolution(analyse.kt:24)
        at org.jetbrains.kotlin.fir.pipeline.FirUtilsKt.resolveAndCheckFir(firUtils.kt:76)
        at org.jetbrains.kotlin.fir.pipeline.FirUtilsKt.buildResolveAndCheckFirViaLightTree(firUtils.kt:88)
        at org.jetbrains.kotlin.cli.js.klib.JsCompilerPipelineKt.compileModulesToAnalyzedFirWithLightTree(jsCompilerPipeline.kt:194)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.processSourceModuleWithK2(K2JSCompiler.kt:661)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.produceSourceModule(K2JSCompiler.kt:560)
```

**Comment by JavierSegoviaCordoba** [comment]
Final version 2.1.0 should be available this week or next I think. I will update with it.

**Comment by JavierSegoviaCordoba** [comment]
@sureshg I have updated to 2.1.0 and everything is passing without touching any file. The publication will be on Maven Central in a few minutes.

**Comment by JavierSegoviaCordoba** [comment]
Published @sureshg, ping me if the issue persists.

**Comment by sureshg** [comment]
Now getting a different error 

```
> Task :shared:compileKotlinWasmJs
e: org.jetbrains.kotlin.util.FileAnalysisException: While analysing /.../shared/src/commonMain/kotlin/dev/suresh/lang/Person.kt:6:1: java.lang.ClassCastException: class org.jetb
rains.kotlin.fir.symbols.impl.ConeClassLikeLookupTagImpl cannot be cast to class org.jetbrains.kotlin.fir.symbols.ConeClassLikeLookupTag (org.jetbrains.kotlin.fir.symbols.impl.ConeClassLikeLookupTagImpl is in unnam
ed module of loader 'app'; org.jetbrains.kotlin.fir.symbols.ConeClassLikeLookupTag is in unnamed module of loader java.net.URLClassLoader @3b73a4cc)
        at org.jetbrains.kotlin.util.AnalysisExceptionsKt.wrapIntoFileAnalysisExceptionIfNeeded(AnalysisExceptions.kt:57)
        at org.jetbrains.kotlin.fir.FirCliExceptionHandler.handleExceptionOnFileAnalysis(Utils.kt:249)
        at org.jetbrains.kotlin.fir.resolve.transformers.AbstractFirStatusResolveTransformer.transformFile(FirStatusResolveTransformer.kt:542)
        at org.jetbrains.kotlin.fir.resolve.transformers.AbstractFirStatusResolveTransformer.transformFile(FirStatusResolveTransformer.kt:187)
        at org.jetbrains.kotlin.fir.declarations.FirFile.transform(FirFile.kt:46)
        at org.jetbrains.kotlin.fir.resolve.transformers.FirTransformerBasedResolveProcessor.processFile(FirResolveProcessor.kt:48)
        at org.jetbrains.kotlin.fir.resolve.transformers.FirTotalResolveProcessor.process(FirTotalResolveProcessor.kt:36)
        at org.jetbrains.kotlin.fir.pipeline.AnalyseKt.runResolution(analyse.kt:24)
        at org.jetbrains.kotlin.fir.pipeline.FirUtilsKt.resolveAndCheckFir(firUtils.kt:76)
        at org.jetbrains.kotlin.fir.pipeline.FirUtilsKt.buildResolveAndCheckFirViaLightTree(firUtils.kt:88)
        at org.jetbrains.kotlin.cli.js.klib.JsCompilerPipelineKt.compileModulesToAnalyzedFirWithLightTree(jsCompilerPipeline.kt:194)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.processSourceModuleWithK2(K2JSCompiler.kt:661)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.produceSourceModule(K2JSCompiler.kt:560)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.kt:345)
        at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.kt:105)

```

**Comment by JavierSegoviaCordoba** [comment]
@sureshg publishing a patch version for this, sorry, I tried to workaround updating the project without updating Hubdle with no luck 👎

**Comment by sureshg** [comment]
@JavierSegoviaCordoba thanks for the fix. `0.13.1+2.1.0` worked fine on all targets. A couple more questions for my understanding:

- Is it still the case to apply the `Kopy` plugin before `atomicfu`?
- Since K2 is now stable, is there any way to auto-disable the `kotlin.k2.only.bundled.compiler.plugins.enabled` config on project import so that other developers can experience autocomplete for copy/invoke functions in the IDE?

**Comment by JavierSegoviaCordoba** [comment]
1. I haven't checked it but probably it didn't changed as there is no way to decide compiler plugin order yet.

2. Sadly, no. FIR APIs are not stable yet.
